---
#高可用节点1的配置
server:
  port: 8771
spring:
  #节点1的标签
  profiles: peer1
  #服务名保持一致
  application:
    name: eureka-highavailable

eureka:
  instance:
    hostname: peer1
  client:
    service-url:
      defaultZone: http://peer2:8772/eureka/,http://peer3:8773/eureka/

---
#高可用节点2的配置
server:
  port: 8772
spring:
  #节点1的标签
  profiles: peer2
  #服务名保持一致
  application:
    name: eureka-highavailable

eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://peer1:8771/eureka/,http://peer3:8773/eureka/

---
#高可用节点3的配置
server:
  port: 8773
spring:
  #节点1的标签
  profiles: peer3
  #服务名保持一致
  application:
    name: eureka-highavailable

eureka:
  instance:
    hostname: peer3
  client:
    service-url:
      defaultZone: http://peer1:8771/eureka/,http://peer2:8772/eureka/
